name: GitHub Actions CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    name: CI
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.x
      uses: actions/setup-go@v2
      with:
        # Run on the latest minor release of Go 1.19:
        go-version: '^1.19'
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Ensure all files were formatted as per gofmt
      run: |
        [ "$(gofmt -l $(find . -name '*.go') 2>&1)" = "" ]

    - name: Install Linux package dependencies
      run: |
        sudo apt update && sudo apt install -y --no-install-recommends slimit yui-compressor zopfli

    - name: Get dependencies
      run: |
        go get -v -t -d ./...

    - name: Go Vet
      run: |
        go vet

    - name: Build
      run: |
        go build -v ./cmd/...

    - name: Test
      run: |
        go test -v ./...
